name: Run Tests and Generate Coverage

on:
  pull_request:
    branches:
      - main  # Adjust this if your main branch is named differently

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install

    - name: Run tests with coverage
      run: |
        poetry run pytest --cov=my_project

    - name: Generate HTML coverage report
      run: |
        poetry run pytest --cov-report html

    - name: Check if HTML coverage report exists
      run: |
        if [ -d "htmlcov" ]; then
          echo "HTML coverage report exists."
          git add htmlcov/
          git commit -m "Add HTML coverage report"
          git push
        else
          echo "HTML coverage report does not exist."
        fi
